fs:
  swagger:
    license: Powered By flash-sloth
    licenseUrl: https://github.com/flash-sloth
    termsOfServiceUrl: https://github.com/flash-sloth
    version: @project.version@
    contact: # 联系人信息
      url: https://github.com/flash-sloth
      name: tangyh
      email: 244387066@qq.com
    global-operation-parameters: # 全局参数
      - name: Token
        description: 用户信息
        modelRef: String
        parameterType: header
        required: true
        # 默认值只是方便本地开发时，少填参数，生产环境请禁用swagger或者禁用默认参数
        defaultValue: "test"
      - name: Authorization
        description: 客户端信息
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "bGFtcF93ZWI6bGFtcF93ZWJfc2VjcmV0"
      - name: TenantId
        description: 租户ID
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "1"

# knife4j 文档通用配置 详情看: Knife4jProperties
knife4j:
  enable: true
  setting:
    enableReloadCacheParameter: true
    enableVersion: true
    enableDynamicParameter: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2024 [flash-sloth](https://github.com/flash-sloth)

springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
      - group: '001_system'
        displayName: '系统功能'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.system
      - group: '005_app'
        displayName: '移动端接口'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.app
      - group: '010_auth'
        displayName: '认证中心'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.auth
      - group: '015_form'
        displayName: '表单引擎'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.form
      - group: '020_generator'
        displayName: '代码生成器'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.generator
      - group: '025_liteflow'
        displayName: '规则引擎'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.liteflow
      - group: '030_magicapi'
        displayName: '在线接口'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.magicapi
      - group: '035_msg'
        displayName: '消息中心'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.msg
      - group: '040_organization'
        displayName: '组织机构'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.organization
      - group: '045_oss'
        displayName: '对象存储'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.oss
      - group: '900_test'
        displayName: '示例代码'
        paths-to-match: '/**'
        packages-to-scan: top.fsfsfs.boot.modules.test