fs:
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
    database: 1

spring:
  cache:
    type: GENERIC
  data:
    redis:
      host: ${fs.redis.ip}
      password: ${fs.redis.password}
      port: ${fs.redis.port}
      database: ${fs.redis.database}
